name: "🐛 Bug Report"
description: Create a bug report to help us improve.
title: "🐛 [BUG] - <title>"
labels: 
  - "bug"
assignees:
  - "ShreyasAyyengar"
body: 
  - type: textarea
    id: summary
    attributes:
      label: "Summary of Bug"
      description: Give us a summary of the current bug
      placeholder: Short and explicit summary of the bug...
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected Behavior"
      description: Tell us what should happen
      placeholder: Expected behavior...
    validations:
      required: true
  - type: textarea
    id: current-behavior
    attributes:
      label: "Current Behavior"
      description: Tell us what happens instead of the expected behavior
      placeholder: Current behavior...
    validations:
      required: true
  - type: textarea
    id: possible-solution
    attributes:
      label: "Possible Solution"
      description: Not obligatory, but suggest a fix/reason for the bug
      placeholder: Possible solution...
    validations:
      required: false
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "Please provide a numbered list of steps to reproduce the bug, e.g. '1. Go to...' "
      placeholder: Steps to reproduce...
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots"
      description: "Please feel free to add screenshots related to this issue."
      placeholder: Screenshots...
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: "Context (Environment)"
      description: Please feel free to add any other context about the problem here.
      placeholder: Context...
    validations:
      required: false
  - type: textarea
    id: possible-implementation
    attributes:
      label: "Possible Implementation"
      description: Not obligatory, but suggest an idea for implementing a solution
      placeholder: Possible implementation...
    validations:
      required: false
