name: "🐛 Bug Report"
description: Create a bug report.
title: "🐛 [BUG] - <title>"
labels: 
  - "bug"
assignees:
  - "ShreyasAyyengar"
body: 
  - type: textarea
    id: summary
    attributes:
      label: "Description of Bug"
      description: Give us a detailed description of the bug.
      placeholder: Detailed summary of the bug, how it looks, what it does.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "Please provide a numbered list of steps to reproduce the bug, e.g. '1. Run `/command`' "
      placeholder: Steps to exactly reproduce...
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected Behavior"
      description: Tell us what should happen
      placeholder: Expected behavior...
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots"
      description: "Please feel free to add screenshots related to this issue."
      placeholder: Screenshots...
    validations:
      required: false
  - type: textarea
    id: possible-solution
    attributes:
      label: "Possible Solution"
      description: Not obligatory, but suggest a fix/reason for the bug
      placeholder: Possible solution...
    validations:
      required: false
